# Generated by Django 4.2.11 on 2024-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
